apiVersion: v1
kind: Template
objects:
  - apiVersion: batch/v1
      kind: Job
      metadata:
        name: flink-jobmanager
      spec:
        template:
          metadata:
            labels:
              app: flink
              component: jobmanager
          spec:
            restartPolicy: OnFailure
            containers:
              - name: jobmanager
                image: flink:1.11.0-scala_2.11
                env:
                  args: ["standalone-job", "--job-classname", "com.job.ClassName", <optional arguments>, <job arguments>] # optional arguments: ["--job-id", "<job id>", "--fromSavepoint", "/path/to/savepoint", "--allowNonRestoredState"]
                ports:
                  - containerPort: 6123
                    name: rpc
                  - containerPort: 6124
                    name: blob-server
                  - containerPort: 8081
                    name: webui
                livenessProbe:
                  tcpSocket:
                    port: 6123
                  initialDelaySeconds: 30
                  periodSeconds: 60
                volumeMounts:
                - name: flink-config-volume
                  mountPath: /opt/flink/conf
                - name: job-artifacts-volume
                  mountPath: /opt/flink/usrlib
            volumes:
            - name: flink-config-volume
              configMap:
                name: flink-config
                items:
                  - key: flink-conf.yaml
                    path: flink-conf.yaml
                  - key: log4j-console.properties
                    path: log4j-console.properties
            - name: job-artifacts-volume
              persistentVolumeClaim:
                claimName: "flink-taskmanager-artifacts-volume"
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      labels:
        app: flink
      name: "flink-taskmanager-artifacts-volume"
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 500Mi
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: flink-taskmanager
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: flink
          component: taskmanager
      template:
        metadata:
          labels:
            app: flink
            component: taskmanager
        spec:
          containers:
          - name: taskmanager
            image: flink:1.11.0-scala_2.11
            env:
            args: ["taskmanager"]
            ports:
            - containerPort: 6122
              name: rpc
            - containerPort: 6125
              name: query-state
            resources:
              limits:
                memory: 1000Mi
              requests:
                memory: 1000Mi
            livenessProbe:
              tcpSocket:
                port: 6122
              initialDelaySeconds: 30
              periodSeconds: 60
            volumeMounts:
            - name: flink-config-volume
              mountPath: /opt/flink/conf/
            - name: job-artifacts-volume
              mountPath: /opt/flink/usrlib
          volumes:
          - name: flink-config-volume
            configMap:
              name: flink-config
              items:
              - key: flink-conf.yaml
                path: flink-conf.yaml
              - key: log4j-console.properties
                path: log4j-console.properties
          - name: job-artifacts-volume
            persistentVolumeClaim:
              claimName: "flink-taskmanager-artifacts-volume"
